#!/bin/bash
# Script to track progress of creating all 15 concepts
echo "Vectors in Quantum Computing - Concept Creation Progress"
echo "=========================================================="
echo ""
echo "Target: 15 concepts total (30 files: 15 HTML + 15 Python)"
echo ""
echo "Status:"
echo "  ✓ Concept 1: Introduction (HTML + Python)"
echo "  ⏳ Concept 2: Mathematical Definition"
echo "  ⏳ Concept 3: Addition & Subtraction"
echo "  ⏳ Concept 4: Scalar Multiplication"
echo "  ⏳ Concept 5: Inner Product"
echo "  ⏳ Concept 6: Norm (Magnitude)"
echo "  ⏳ Concept 7: Basis Vectors"
echo "  ⏳ Concept 8: Orthogonality"
echo "  ⏳ Concept 9: Linear Independence"
echo "  ⏳ Concept 10: Multi-Qubit Systems"
echo "  ⏳ Concept 11: Vector Transformations"
echo "  ⏳ Concept 12: Outer Product"
echo "  ⏳ Concept 13: Bloch Sphere"
echo "  ⏳ Concept 14: Exercises (5 exercises)"
echo "  ⏳ Concept 15: Summary"
echo ""
echo "Progress: 1/15 concepts complete (6.7%)"
echo "Files created: 3/30 (10%)"
